database_id: 'd3e3be7fc96a45de8e7d3a78298f9ccd'
MAX_RESULTS_PER_PAGE: 25
PDF_DOWNLOAD_ROOT: 'E:\OneDrive - Harvard University\openai-emb-database\arxiv_pdf'
EMBED_ROOTDIR: 'E:\OneDrive - Harvard University\openai-emb-database\Embed_data'